// stream
export const FETCH_LIVE_STREAM = 'FETCH_LIVE_STREAM';
export const FETCH_SCHEDULED_STREAM = 'FETCH_SCHEDULED_STREAM';
export const FETCH_CHANNEL = 'FETCH_CHANNEL';
export const FETCH_MEMBER = 'FETCH_MEMBER';

// multi view
export const ADD_STREAM_TO_MULTI_VIEW = 'ADD_STREAM_TO_MULTI_VIEW';
export const REMOVE_STREAM_FROM_MULTI_VIEW = 'REMOVE_STREAM_FROM_MULTI_VIEW';
export const CHANGE_STATUS_TO_PLAY = 'CHANGE_STATUS_TO_PLAY';
export const CHANGE_STATUS_TO_PAUSE = 'CHANGE_STATUS_TO_PAUSE';
export const CHANGE_STATUS_TO_MUTE = 'CHANGE_STATUS_TO_MUTE';
export const CHANGE_STATUS_TO_UNMUTE = 'CHANGE_STATUS_TO_UNMUTE';
export const SHOW_CHAT = 'SHOW_CHAT';
export const HIDE_CHAT = 'HIDE_CHAT';
