export const STREAM_ACTION_TYPES = {
  REQUEST_LIVE_STREAM: 'stream/REQUEST_LIVE_STREAM',
  RECEIVE_LIVE_STREAM: 'stream/RECEIVE_LIVE_STREAM',
  REQUEST_SCHEDULED_STREAM: 'stream/REQUEST_SCHEDULED_STREAM',
  RECEIVE_SCHEDULED_STREAM: 'stream/RECEIVE_SCHEDULED_STREAM',
  FETCH_CHANNEL: 'stream/FETCH_CHANNEL',
  FETCH_MEMBER: 'stream/FETCH_MEMBER',
};
