export const MULTIVIEW_ACTION_TYPES = {
  ADD_STREAM_TO_MULTI_VIEW: 'multi-view/ADD_STREAM_TO_MULTI_VIEW',
  REMOVE_STREAM_FROM_MULTI_VIEW: 'multi-view/REMOVE_STREAM_FROM_MULTI_VIEW',
  CHANGE_STATUS_TO_PLAY: 'multi-view/CHANGE_STATUS_TO_PLAY',
  CHANGE_STATUS_TO_PAUSE: 'multi-view/CHANGE_STATUS_TO_PAUSE',
  CHANGE_STATUS_TO_MUTE: 'multi-view/CHANGE_STATUS_TO_MUTE',
  CHANGE_STATUS_TO_UNMUTE: 'multi-view/CHANGE_STATUS_TO_UNMUTE',
  SHOW_CHAT: 'multi-view/SHOW_CHAT',
  HIDE_CHAT: 'multi-view/HIDE_CHAT',
};
